# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: ""
description: > # this means to ignore newlines until "email:"
   The Dabblings of a Data Scientist

email: parveenkaursarana@gmail.com
#blog logo
logo: "/assets/images/pk_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/clean_lemons.jpg

name: 'Parveen Kaur'
author: 'Parveen Kaur'
author_image: "/assets/images/unnamed.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@pklemon'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/pklemon
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/psarana
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
